//! Code generation: converts parsed IDL type definitions to Rust source code.
//!
//! The generated code uses the derive macros from `cyclonedds-derive`:
//! - `DdsType` for structs
//! - `DdsEnum` for enums
//! - `DdsUnion` for unions
//! - `DdsBitmask` for bitmasks

use crate::idl_parser::{
    Definition, IdlBitmask, IdlEnum, IdlFile, IdlModule, IdlStruct, IdlType, IdlTypeRef, IdlUnion,
    PrimitiveType,
};
use crate::CompileOptions;

/// Outer allow applied to each generated item so the file can be `include!`d.
///
/// A crate-level `#![allow(...)]` cannot be `include!`d into a module, so the
/// allow is attached to each item instead.
const ITEM_ALLOW: &str = "#[allow(dead_code, non_camel_case_types, non_snake_case)]\n";

/// Generate a complete Rust source file from a parsed IDL file.
pub fn generate_rust(idl_file: &IdlFile, module_name: &str) -> String {
    generate_rust_with_options(idl_file, module_name, &CompileOptions::default())
}

/// Generate a complete Rust source file with custom options.
pub fn generate_rust_with_options(
    idl_file: &IdlFile,
    module_name: &str,
    options: &CompileOptions,
) -> String {
    let mut output = String::new();

    output.push_str("// @generated by cyclonedds-build. DO NOT EDIT.\n");
    output.push_str("// Source IDL module: ");
    output.push_str(module_name);
    output.push_str("\n\n");
    output.push_str("#[allow(unused_imports)]\n");
    output.push_str(
        "use cyclonedds::{DdsTypeDerive, DdsEnumDerive, DdsUnionDerive, DdsBitmaskDerive};\n",
    );
    output.push_str("#[allow(unused_imports)]\n");
    output.push_str("use cyclonedds::{DdsSequence, DdsBoundedSequence, DdsString};\n\n");

    // Generate top-level definitions (types and nested modules)
    for def in &idl_file.definitions {
        output.push_str(&generate_definition(def, &[], options));
        output.push('\n');
    }

    output
}

/// Generate Rust code for a definition: a type or a nested module.
fn generate_definition(def: &Definition, scope: &[&str], options: &CompileOptions) -> String {
    match def {
        Definition::Type(ty) => generate_type(ty, scope, options),
        Definition::Module(m) => generate_module(m, scope, options),
    }
}

/// Generate a Rust module wrapping a set of definitions.
fn generate_module(m: &IdlModule, scope: &[&str], options: &CompileOptions) -> String {
    let mut output = String::new();
    output.push_str(ITEM_ALLOW);
    output.push_str("pub mod ");
    output.push_str(&to_snake_case(&m.name));
    output.push_str(" {\n");
    output.push_str("    use super::*;\n\n");

    let mut child_scope: Vec<&str> = scope.to_vec();
    child_scope.push(m.name.as_str());

    for child in &m.definitions {
        output.push_str(&indent(
            &generate_definition(child, &child_scope, options),
            4,
        ));
        output.push('\n');
    }

    output.push_str("}\n");
    output
}

/// Indent every non-empty line of `code` by `spaces` spaces.
fn indent(code: &str, spaces: usize) -> String {
    let pad = " ".repeat(spaces);
    let mut out = String::new();
    for line in code.lines() {
        if !line.is_empty() {
            out.push_str(&pad);
        }
        out.push_str(line);
        out.push('\n');
    }
    out
}

/// Generate Rust code for a single IDL type definition.
fn generate_type(ty: &IdlType, scope: &[&str], options: &CompileOptions) -> String {
    match ty {
        IdlType::Struct(s) => generate_struct(s, scope, options),
        IdlType::Enum(e) => generate_enum(e),
        IdlType::Union(u) => generate_union(u),
        IdlType::Bitmask(b) => generate_bitmask(b),
        IdlType::Typedef(td) => generate_typedef(td),
    }
}

/// Join a module scope and a type name into a fully-qualified IDL name.
fn qualified_name(scope: &[&str], name: &str) -> String {
    if scope.is_empty() {
        name.to_string()
    } else {
        format!("{}::{}", scope.join("::"), name)
    }
}

/// Generate a Rust struct with `#[derive(DdsType)]`.
fn generate_struct(s: &IdlStruct, scope: &[&str], options: &CompileOptions) -> String {
    let mut output = String::new();

    output.push_str(ITEM_ALLOW);
    output.push_str("#[derive(Debug, Clone, Default, PartialEq, DdsTypeDerive)]\n");
    if options.emit_dds_typename {
        output.push_str("#[dds_typename(\"");
        output.push_str(&qualified_name(scope, &s.name));
        output.push_str("\")]\n");
    }
    output.push_str("pub struct ");
    output.push_str(&s.name);
    output.push_str(" {\n");

    for field in &s.fields {
        // Generate field annotations
        for ann in &field.annotations {
            match ann.name.as_str() {
                "key" => output.push_str("    #[key]\n"),
                "position" | "id" | "hash_id" => {
                    // These are IDL-level annotations; the derive macro handles them
                    // via the op descriptor layout. No Rust attribute needed for now.
                }
                _ => {}
            }
        }

        output.push_str("    pub ");
        output.push_str(&field.name);
        output.push_str(": ");
        output.push_str(&type_ref_to_rust(&field.ty));
        output.push_str(",\n");
    }

    output.push_str("}\n");
    output
}

/// Generate a Rust enum with `#[derive(DdsEnum)]`.
fn generate_enum(e: &IdlEnum) -> String {
    let mut output = String::new();

    output.push_str(ITEM_ALLOW);
    output.push_str("#[repr(i32)]\n");
    output.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, DdsEnumDerive)]\n");
    output.push_str("pub enum ");
    output.push_str(&e.name);
    output.push_str(" {\n");

    for variant in &e.variants {
        output.push_str("    ");
        output.push_str(&variant.name);
        if let Some(val) = variant.value {
            output.push_str(" = ");
            output.push_str(&val.to_string());
        }
        output.push_str(",\n");
    }

    output.push_str("}\n");
    output
}

/// Generate a Rust enum with `#[derive(DdsUnion)]`.
fn generate_union(u: &IdlUnion) -> String {
    let mut output = String::new();

    output.push_str(ITEM_ALLOW);
    output.push_str("#[derive(Debug, Clone, DdsUnionDerive)]\n");
    output.push_str("#[dds_discriminant(");
    output.push_str(&type_ref_to_rust(&u.discriminant_type));
    output.push_str(")]\n");
    output.push_str("pub enum ");
    output.push_str(&u.name);
    output.push_str(" {\n");

    for case in &u.cases {
        for &label in &case.label_values {
            output.push_str("    #[dds_case(");
            output.push_str(&label.to_string());
            output.push_str(")]\n");
        }
        output.push_str("    ");
        output.push_str(&to_pascal_case(&case.name));
        output.push('(');
        output.push_str(&type_ref_to_rust(&case.ty));
        output.push_str("),\n");
    }

    if let Some(default) = &u.default_case {
        output.push_str("    #[dds_default]\n");
        output.push_str("    ");
        output.push_str(&to_pascal_case(&default.name));
        output.push('(');
        output.push_str(&type_ref_to_rust(&default.ty));
        output.push_str("),\n");
    }

    output.push_str("}\n");
    output
}

/// Generate a Rust struct with `#[derive(DdsBitmask)]`.
fn generate_bitmask(b: &IdlBitmask) -> String {
    let mut output = String::new();

    output.push_str(ITEM_ALLOW);
    output.push_str("#[derive(Debug, Clone, DdsBitmaskDerive)]\n");
    output.push_str("#[bit_bound(");
    output.push_str(&b.bit_bound.to_string());
    output.push_str(")]\n");
    output.push_str("pub struct ");
    output.push_str(&b.name);
    output.push_str(" {\n");

    for flag in &b.flags {
        output.push_str("    pub ");
        output.push_str(flag);
        output.push_str(": bool,\n");
    }

    output.push_str("}\n");
    output
}

/// Generate a Rust type alias for a typedef.
fn generate_typedef(td: &crate::idl_parser::IdlTypedef) -> String {
    let mut output = String::new();
    output.push_str(ITEM_ALLOW);
    output.push_str("pub type ");
    output.push_str(&td.name);
    output.push_str(" = ");
    output.push_str(&type_ref_to_rust(&td.ty));
    output.push_str(";\n");
    output
}

/// Map an IDL type reference to a Rust type string.
fn type_ref_to_rust(ty: &IdlTypeRef) -> String {
    match ty {
        IdlTypeRef::Primitive(p) => primitive_to_rust(*p).to_string(),
        IdlTypeRef::String { bound: None } => "String".to_string(),
        IdlTypeRef::String { bound: Some(_n) } => {
            // Bounded strings use DdsString in the current derive macro
            "DdsString".to_string()
        }
        IdlTypeRef::Sequence {
            element_type,
            bound: None,
        } => {
            format!("DdsSequence<{}>", type_ref_to_rust(element_type))
        }
        IdlTypeRef::Sequence {
            element_type,
            bound: Some(max),
        } => {
            format!(
                "DdsBoundedSequence<{}, {}>",
                type_ref_to_rust(element_type),
                max
            )
        }
        IdlTypeRef::Array { element_type, size } => {
            format!("[{}; {}]", type_ref_to_rust(element_type), size)
        }
        IdlTypeRef::Named(name) => {
            // Strip leading :: if present, and use the simple name
            let clean = name.trim_start_matches("::");
            // For scoped names like Module::Type, just use the last segment
            // as the user is expected to import or use the correct path
            if let Some(last) = clean.rsplit("::").next() {
                last.to_string()
            } else {
                clean.to_string()
            }
        }
    }
}

/// Map an IDL primitive type to a Rust type.
fn primitive_to_rust(p: PrimitiveType) -> &'static str {
    match p {
        PrimitiveType::Boolean => "bool",
        PrimitiveType::Octet => "u8",
        PrimitiveType::Char => "u8",
        PrimitiveType::Wchar => "u16",
        PrimitiveType::Short => "i16",
        PrimitiveType::UnsignedShort => "u16",
        PrimitiveType::Long => "i32",
        PrimitiveType::UnsignedLong => "u32",
        PrimitiveType::LongLong => "i64",
        PrimitiveType::UnsignedLongLong => "u64",
        PrimitiveType::Float => "f32",
        PrimitiveType::Double => "f64",
        PrimitiveType::LongDouble => "f64", // Rust has no f128; approximate with f64
    }
}

/// Convert a snake_case or lowercase string to PascalCase.
fn to_pascal_case(s: &str) -> String {
    s.split('_')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                None => String::new(),
                Some(c) => {
                    let upper = c.to_uppercase().to_string();
                    format!("{}{}", upper, chars.as_str())
                }
            }
        })
        .collect()
}

/// Convert a CamelCase string to snake_case.
fn to_snake_case(s: &str) -> String {
    let mut result = String::new();
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() {
            if i > 0 {
                result.push('_');
            }
            result.push(c.to_ascii_lowercase());
        } else {
            result.push(c);
        }
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::idl_parser::{IdlEnumVariant, IdlField};

    #[test]
    fn test_generate_simple_struct() {
        let s = IdlStruct {
            name: "Point".into(),
            fields: vec![
                IdlField {
                    name: "x".into(),
                    ty: IdlTypeRef::Primitive(PrimitiveType::Long),
                    annotations: vec![],
                },
                IdlField {
                    name: "y".into(),
                    ty: IdlTypeRef::Primitive(PrimitiveType::Double),
                    annotations: vec![],
                },
            ],
            annotations: vec![],
        };
        let code = generate_struct(&s, &[], &CompileOptions::default());
        assert!(code.contains("#[derive(Debug, Clone, Default, PartialEq, DdsTypeDerive)]"));
        assert!(code.contains("#[dds_typename(\"Point\")]"));
        assert!(code.contains("pub struct Point"));
        assert!(code.contains("pub x: i32"));
        assert!(code.contains("pub y: f64"));
    }

    #[test]
    fn test_generate_enum() {
        let e = IdlEnum {
            name: "Color".into(),
            variants: vec![
                IdlEnumVariant {
                    name: "Red".into(),
                    value: Some(0),
                },
                IdlEnumVariant {
                    name: "Green".into(),
                    value: Some(1),
                },
                IdlEnumVariant {
                    name: "Blue".into(),
                    value: Some(2),
                },
            ],
        };
        let code = generate_enum(&e);
        assert!(code.contains("#[repr(i32)]"));
        assert!(code.contains("#[derive(Debug, Clone, Copy, PartialEq, Eq, DdsEnumDerive)]"));
        assert!(code.contains("Red = 0"));
        assert!(code.contains("Blue = 2"));
    }

    #[test]
    fn test_type_ref_mapping() {
        assert_eq!(
            type_ref_to_rust(&IdlTypeRef::Primitive(PrimitiveType::Boolean)),
            "bool"
        );
        assert_eq!(
            type_ref_to_rust(&IdlTypeRef::Primitive(PrimitiveType::Long)),
            "i32"
        );
        assert_eq!(
            type_ref_to_rust(&IdlTypeRef::Primitive(PrimitiveType::UnsignedLongLong)),
            "u64"
        );
        assert_eq!(
            type_ref_to_rust(&IdlTypeRef::String { bound: None }),
            "String"
        );
        assert_eq!(
            type_ref_to_rust(&IdlTypeRef::Named("MyType".into())),
            "MyType"
        );
    }

    #[test]
    fn test_generate_bitmask() {
        let b = IdlBitmask {
            name: "Flags".into(),
            bit_bound: 16,
            flags: vec!["Ready".into(), "Active".into()],
        };
        let code = generate_bitmask(&b);
        assert!(code.contains("#[derive(Debug, Clone, DdsBitmaskDerive)]"));
        assert!(code.contains("#[bit_bound(16)]"));
        assert!(code.contains("pub Ready: bool"));
    }

    #[test]
    fn test_generate_nested_modules() {
        let file = IdlFile {
            definitions: vec![Definition::Module(IdlModule {
                name: "dds".into(),
                definitions: vec![Definition::Module(IdlModule {
                    name: "hello_world".into(),
                    definitions: vec![Definition::Type(IdlType::Struct(IdlStruct {
                        name: "HelloWorldModel".into(),
                        fields: vec![IdlField {
                            name: "id".into(),
                            ty: IdlTypeRef::Primitive(PrimitiveType::Long),
                            annotations: vec![],
                        }],
                        annotations: vec![],
                    }))],
                })],
            })],
        };
        let code = generate_rust(&file, "nested_modules");
        assert!(code.contains("pub mod dds {"));
        assert!(code.contains("pub mod hello_world {"));
        assert!(code.contains("pub struct HelloWorldModel"));
        assert!(code.contains("#[dds_typename(\"dds::hello_world::HelloWorldModel\")]"));
    }

    #[test]
    fn test_generate_dds_typename_disabled() {
        let s = IdlStruct {
            name: "Point".into(),
            fields: vec![],
            annotations: vec![],
        };
        let options = CompileOptions {
            emit_dds_typename: false,
            ..Default::default()
        };
        let code = generate_struct(&s, &["dds", "hello_world"], &options);
        assert!(!code.contains("dds_typename"));
    }

    #[test]
    fn test_generate_dds_typename_top_level() {
        let s = IdlStruct {
            name: "Point".into(),
            fields: vec![],
            annotations: vec![],
        };
        let code = generate_struct(&s, &[], &CompileOptions::default());
        assert!(code.contains("#[dds_typename(\"Point\")]"));
    }
}
